/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import dao.EmpruntDao;
import entities.Emprunt;
import entities.Livre;
import entities.Membre;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.EmpruntService;
import service.LivreService;
import service.MembreService;

/**
 *
 * @author HP
 */
public class Emprunt_Frame extends javax.swing.JInternalFrame {

    private LivreService ls;
    private MembreService ms;
    private EmpruntService es;
    private EmpruntDao dao;
    private DefaultTableModel model = null;
    private DefaultTableModel modelH = null;
    private int id;
    Livre livre;
    Membre membre;
    Date dateE;
    Date dateR;

    /**
     * Creates new form Emprunt_Frame
     */
    public Emprunt_Frame() {
        initComponents();

        ls = new LivreService();
        ms = new MembreService();
        es = new EmpruntService();
        dao = new EmpruntDao();

        model = (DefaultTableModel) emprunt_table.getModel();
        modelH = (DefaultTableModel) histoire_table.getModel();

        loadLivres();
        loadMembres();
        if (membre_list.getItemCount() > 0) {
            membre_list.setSelectedIndex(0);
        }
        membre_list.addActionListener(e -> loadHistorique());
        loadHistorique();

        try {
            loadEmprunt();
        } catch (Exception ex) {
            Logger.getLogger(Emprunt_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        retour_btn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        livre_list = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        membre_list = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        emprunt_date = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        retour_date = new com.toedter.calendar.JDateChooser();
        emprunt_btn = new javax.swing.JButton();
        retour_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        emprunt_table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        histoire_table = new javax.swing.JTable();
        tmp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1014, 630));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        livre_list.setPreferredSize(new java.awt.Dimension(40, 26));
        livre_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livre_listActionPerformed(evt);
            }
        });

        jLabel1.setText("Livre");

        jLabel2.setText("Membre");

        membre_list.setPreferredSize(new java.awt.Dimension(40, 26));
        membre_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membre_listMouseClicked(evt);
            }
        });

        jLabel3.setText("Date d'emprunt");

        jLabel4.setText("Date de retour");

        emprunt_btn.setText("َEmprunter");
        emprunt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprunt_btnActionPerformed(evt);
            }
        });

        retour_btn.setText("Retour");
        retour_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(retour_date, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emprunt_date, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(membre_list, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(livre_list, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(emprunt_btn)
                        .addGap(131, 131, 131)
                        .addComponent(retour_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(livre_list, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(membre_list, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emprunt_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retour_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emprunt_btn)
                    .addComponent(retour_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(165, 165, 165))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List des emprunts", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        emprunt_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Livre", "Membre", "Date d'emprunt", "Date de retour", "Status"
            }
        ));
        emprunt_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emprunt_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(emprunt_table);

        histoire_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Livre", "Date d'emprunt", "Date de retour", "Status"
            }
        ));
        jScrollPane3.setViewportView(histoire_table);

        tmp.setText("memebre");
        tmp.setAlignmentX(0.5F);

        jLabel5.setText("Historique :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmp)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livre_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livre_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_livre_listActionPerformed

    private void emprunt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprunt_btnActionPerformed
        Livre livre = (Livre) livre_list.getSelectedItem();
        Membre membre = (Membre) membre_list.getSelectedItem();
        Date dateE = emprunt_date.getDate();
        Date dateR = retour_date.getDate();

        if (livre == null || membre == null || dateE == null || dateR == null) {
            JOptionPane.showMessageDialog(this, "Remplez vous tous les champs!");
        }
        try {
            es.empruntLivre(new Emprunt(livre, membre, dateE, dateR));
            loadEmprunt();
            vider();
        } catch (Exception ex) {
            Logger.getLogger(Emprunt_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_emprunt_btnActionPerformed

    private void emprunt_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprunt_tableMouseClicked
        retour_btn.setEnabled(true);
        id = Integer.parseInt(model.getValueAt(emprunt_table.getSelectedRow(), 0).toString());
        livre = (Livre) model.getValueAt(emprunt_table.getSelectedRow(), 1);
        membre = (Membre) model.getValueAt(emprunt_table.getSelectedRow(), 2);
        dateE = (Date) model.getValueAt(emprunt_table.getSelectedRow(), 3);
        dateR = (Date) model.getValueAt(emprunt_table.getSelectedRow(), 4);
    }//GEN-LAST:event_emprunt_tableMouseClicked

    private void retour_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour_btnActionPerformed
        try {
            es.retourLivre(new Emprunt(id, livre, membre, dateE, dateR));
            loadEmprunt();
            retour_btn.setEnabled(false);
            vider();
        } catch (Exception ex) {
            Logger.getLogger(Emprunt_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retour_btnActionPerformed

    private void membre_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membre_listMouseClicked

    }//GEN-LAST:event_membre_listMouseClicked

    private void loadHistorique() {
        Membre membres = (Membre) membre_list.getSelectedItem();

        if (membres == null) {
            return;
        }

        tmp.setText(membres.getNom());
        Date date = new Date();
        String status;
        modelH.setRowCount(0);
        try {
            for (Emprunt m : es.membreHistorique(membres)) {
                if (m == null || m.getDateRetour() == null) {
                    continue;
                }
                if (m.getDateRetour().before(date)) {
                    status = "en retard";
                } else {
                    status = "emprunte";
                }
                modelH.addRow(new Object[]{
                    m.getId(),
                    m.getLivre(),
                    m.getDateEmprunt(),
                    m.getDateRetour(),
                    status
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(Emprunt_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadLivres() {
        try {
            for (Livre l : ls.listLivres()) {
                livre_list.addItem(l);
            }
        } catch (Exception ex) {
            Logger.getLogger(Emprunt_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadMembres() {
        try {
            for (Membre m : ms.listMembres()) {
                membre_list.addItem(m);
            }
        } catch (Exception ex) {
            Logger.getLogger(Emprunt_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadEmprunt() throws Exception {
        Date date = new Date();
        String status;
        model.setRowCount(0);
        try {
            for (Emprunt e : es.listEmrunt()) {
                if (e.getDateRetour().before(date)) {
                    status = "en retard";
                } else {
                    status = "emprunte";
                }
                model.addRow(new Object[]{
                    e.getId(),
                    e.getLivre(),
                    e.getMembre(),
                    e.getDateEmprunt(),
                    e.getDateRetour(),
                    status
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(Emprunt_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void vider() {
        dateE = null;
        dateR = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emprunt_btn;
    private com.toedter.calendar.JDateChooser emprunt_date;
    private javax.swing.JTable emprunt_table;
    private javax.swing.JTable histoire_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox livre_list;
    private javax.swing.JComboBox membre_list;
    private javax.swing.JButton retour_btn;
    private com.toedter.calendar.JDateChooser retour_date;
    private javax.swing.JLabel tmp;
    // End of variables declaration//GEN-END:variables
}
