/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import entities.Livre;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.LivreService;

/**
 *
 * @author HP
 */
public class Livre_Frame extends javax.swing.JInternalFrame {

    private LivreService ls;
    private DefaultTableModel model = null;
    private int id;

    /**
     * Creates new form Livre_Frame
     */
    public Livre_Frame() {
        initComponents();

        ls = new LivreService();

        model = (DefaultTableModel) livreTable.getModel();

        filter_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    String selected = filtre_list.getSelectedItem().toString();
                    if (selected.equals("par genre")) {
                        filtreGenre();
                    } else if (selected.equals("par auteur")) {
                        filtreAuteur();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erreur : " + ex.getMessage());
                }
            }
        });

        filter_txt.setEnabled(false);
        mod_btn.setEnabled(false);
        supp_btn.setEnabled(false);

        try {
            loadLivres();
        } catch (Exception ex) {
            Logger.getLogger(Livre_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        titre_txt = new javax.swing.JTextField();
        auteur_txt = new javax.swing.JTextField();
        genre_txt = new javax.swing.JTextField();
        ajou_btn = new javax.swing.JButton();
        mod_btn = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        livreTable = new javax.swing.JTable();
        supp_btn = new javax.swing.JButton();
        filtre_list = new javax.swing.JComboBox();
        filter_txt = new javax.swing.JTextField();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Titre");

        jLabel2.setText("Auteur");

        jLabel3.setText("Genre");

        jLabel4.setText("Date de Publication");

        titre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titre_txtActionPerformed(evt);
            }
        });

        ajou_btn.setText("Ajouter");
        ajou_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajou_btnActionPerformed(evt);
            }
        });

        mod_btn.setText("Modifier");
        mod_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titre_txt)
                    .addComponent(auteur_txt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ajou_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mod_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(genre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(auteur_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(genre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mod_btn)
                    .addComponent(ajou_btn))
                .addGap(62, 62, 62))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List des livres", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        livreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livre_id", "Titre", "Auteur", "Genre", "Date de publication"
            }
        ));
        livreTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                livreTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(livreTable);

        supp_btn.setText("Supprimer");
        supp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_btnActionPerformed(evt);
            }
        });

        filtre_list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<par defaut>", "par genre", "par auteur" }));
        filtre_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtre_listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtre_list, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filter_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(supp_btn)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtre_list, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titre_txtActionPerformed

    private void ajou_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajou_btnActionPerformed
        String titre = titre_txt.getText().trim();
        String auteur = auteur_txt.getText().trim();
        String genre = genre_txt.getText().trim();
        Date dateP = date.getDate();

        if (titre.isEmpty() || auteur.isEmpty() || genre.isEmpty() || dateP == null) {
            JOptionPane.showMessageDialog(this, "Remplez vous tous les champs!");
            return;
        }

        try {
            ls.creatLivre(new Livre(titre, auteur, genre, dateP));
            loadLivres();
            vider();
        } catch (Exception ex) {
            Logger.getLogger(Livre_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ajou_btnActionPerformed

    private void mod_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_btnActionPerformed
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier ce livre!");

        if (titre_txt.getText().isEmpty() || auteur_txt.getText().isEmpty() || genre_txt.getText().isEmpty() || date == null) {
            JOptionPane.showMessageDialog(this, "Un champ est vide");
            return;
        }

        if (reponse == 0) {
            try {
                ls.updateLivre(new Livre(id, titre_txt.getText().toString(), auteur_txt.getText().toString(), genre_txt.getText().toString(), date.getDate()));
                loadLivres();
                vider();
                mod_btn.setEnabled(false);
                supp_btn.setEnabled(false);
            } catch (Exception ex) {
                Logger.getLogger(Livre_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mod_btnActionPerformed

    private void livreTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livreTableMouseClicked
        mod_btn.setEnabled(true);
        supp_btn.setEnabled(true);
        id = Integer.parseInt(livreTable.getValueAt(livreTable.getSelectedRow(), 0).toString());
        titre_txt.setText(model.getValueAt(livreTable.getSelectedRow(), 1).toString());
        auteur_txt.setText(model.getValueAt(livreTable.getSelectedRow(), 2).toString());
        genre_txt.setText(model.getValueAt(livreTable.getSelectedRow(), 3).toString());
        date.setDate((Date) model.getValueAt(livreTable.getSelectedRow(), 4));
    }//GEN-LAST:event_livreTableMouseClicked

    private void supp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_btnActionPerformed
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer ce livre!");

        if (reponse == 0) {
            try {
                if (ls.deleteLivre(new Livre(id, titre_txt.getText().toString(), auteur_txt.getText().toString(), genre_txt.getText().toString(), date.getDate()))) {
                    loadLivres();
                    vider();
                    supp_btn.setEnabled(false);
                    mod_btn.setEnabled(false);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Erreur!",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_supp_btnActionPerformed


    private void filtre_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtre_listActionPerformed

        try {
            String selected = filtre_list.getSelectedItem().toString();
            switch (selected) {
                case "<par defaut>":
                    filter_txt.setEnabled(false);
                    filter_txt.setText("");
                    loadLivres();
                    break;
                case "par genre":
                case "par auteur":
                    filter_txt.setEnabled(true);
                    filter_txt.setText("");
                    break;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage());
        }
    }//GEN-LAST:event_filtre_listActionPerformed

    public void filtreGenre() throws Exception {
        String genre = filter_txt.getText().trim();

        if (genre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un genre !");
            return;
        }

        List<Livre> list = ls.filtreGenre(genre);
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aucun Livre trouve!");
        }

        model.setRowCount(0);
        for (Livre l : list) {
            model.addRow(new Object[]{
                l.getId(),
                l.getTitre(),
                l.getAuteur(),
                l.getGenre(),
                l.getAnneePublication()
            });
        }
    }

    public void filtreAuteur() throws Exception {
        String auteur = filter_txt.getText().trim();

        if (auteur.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un auteur !");
            return;
        }

        List<Livre> list = ls.filtreAuteur(auteur);
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aucun Livre trouve!");
        }

        model.setRowCount(0);
        for (Livre l : list) {
            model.addRow(new Object[]{
                l.getId(),
                l.getTitre(),
                l.getAuteur(),
                l.getGenre(),
                l.getAnneePublication()
            });
        }
    }

    public void loadLivres() throws Exception {

        List<Livre> list = ls.listLivres();
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aucun Livre trouve!");
        }

        model.setRowCount(0);
        for (Livre l : list) {
            model.addRow(new Object[]{
                l.getId(),
                l.getTitre(),
                l.getAuteur(),
                l.getGenre(),
                l.getAnneePublication()
            });
        }
    }

    public void vider() {
        titre_txt.setText("");
        auteur_txt.setText("");
        genre_txt.setText("");
        date.setDate(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajou_btn;
    private javax.swing.JTextField auteur_txt;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField filter_txt;
    private javax.swing.JComboBox filtre_list;
    private javax.swing.JTextField genre_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable livreTable;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton mod_btn;
    private javax.swing.JButton supp_btn;
    private javax.swing.JTextField titre_txt;
    // End of variables declaration//GEN-END:variables
}
