/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author HP
 */
public class mainApp extends javax.swing.JFrame {
    
    /**
     * Creates new form mainApp
     */
    public mainApp() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }
    
    private void openInternalFrame(javax.swing.JInternalFrame frame) {
        desktopPane.add(frame);
        frame.setVisible(true);
        try {
            frame.setSelected(true);
        } catch (Exception e) {
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        livreMenuItem = new javax.swing.JMenuItem();
        membreMenuItem = new javax.swing.JMenuItem();
        EmpruntMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        livreMenuItem.setMnemonic('o');
        livreMenuItem.setText("Livre");
        livreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livreMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(livreMenuItem);

        membreMenuItem.setMnemonic('s');
        membreMenuItem.setText("Membres");
        membreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membreMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(membreMenuItem);

        EmpruntMenuItem.setMnemonic('a');
        EmpruntMenuItem.setText("Emprunts");
        EmpruntMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpruntMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(EmpruntMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("statistiques");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("graph");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void livreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livreMenuItemActionPerformed
        openInternalFrame(new Livre_Frame());
    }//GEN-LAST:event_livreMenuItemActionPerformed

    private void membreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membreMenuItemActionPerformed
        openInternalFrame(new Membre_Frame());
    }//GEN-LAST:event_membreMenuItemActionPerformed

    private void EmpruntMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpruntMenuItemActionPerformed
        openInternalFrame(new Emprunt_Frame());
    }//GEN-LAST:event_EmpruntMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        openInternalFrame(new Graph_frame());
    }//GEN-LAST:event_cutMenuItemActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EmpruntMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem livreMenuItem;
    private javax.swing.JMenuItem membreMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
