/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import entities.Membre;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.MembreService;

/**
 *
 * @author HP
 */
public class Membre_Frame extends javax.swing.JInternalFrame {

    private MembreService ms;
    private DefaultTableModel model = null;
    private int id;

    /**
     * Creates new form Membre_Frame
     */
    public Membre_Frame() {
        initComponents();

        ms = new MembreService();

        model = (DefaultTableModel) membres_table.getModel();

        mod_btn.setEnabled(false);
        supp_btn.setEnabled(false);

        LoadMembres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        ajou_btn = new javax.swing.JButton();
        mod_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        membres_table = new javax.swing.JTable();
        supp_btn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setPreferredSize(new java.awt.Dimension(356, 544));

        jLabel1.setText("Nom");

        jLabel2.setText("Email");

        jLabel3.setText("Date d'inscription");

        nom_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_txtActionPerformed(evt);
            }
        });

        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });

        date.setPreferredSize(new java.awt.Dimension(6, 26));

        ajou_btn.setText("Ajouter");
        ajou_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajou_btnActionPerformed(evt);
            }
        });

        mod_btn.setText("Modifier");
        mod_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nom_txt)
                    .addComponent(email_txt)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ajou_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(mod_btn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom_txt)
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_txt)
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajou_btn)
                    .addComponent(mod_btn))
                .addGap(60, 60, 60))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List des membres", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setPreferredSize(new java.awt.Dimension(6, 26));

        membres_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Email", "Date d'inscription"
            }
        ));
        membres_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membres_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(membres_table);

        supp_btn.setText("Supprimer");
        supp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(supp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(supp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void nom_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_txtActionPerformed

    private void ajou_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajou_btnActionPerformed
        String nom = nom_txt.getText().trim();
        String email = email_txt.getText().trim();
        Date dateI = date.getDate();

        if (nom.isEmpty() || email.isEmpty() || dateI == null) {
            JOptionPane.showMessageDialog(this, "Remplez vous tous les champs!");
            return;
        }

        try {
            ms.creatMembre(new Membre(nom, email, dateI));
            LoadMembres();
            vider();
        } catch (Exception ex) {
            Logger.getLogger(Membre_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ajou_btnActionPerformed

    private void supp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_btnActionPerformed
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous supprimer ce membre!");

        if (reponse == 0) {
            try {
                if (ms.deleteMembre(new Membre(id, nom_txt.getText(), email_txt.getText(), date.getDate()))) {
                    LoadMembres();
                    vider();
                    supp_btn.setEnabled(false);
                    mod_btn.setEnabled(false);
                }
            } catch (Exception ex) {
                Logger.getLogger(Membre_Frame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Erreur!",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_supp_btnActionPerformed

    private void membres_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membres_tableMouseClicked
        mod_btn.setEnabled(true);
        supp_btn.setEnabled(true);

        id = Integer.parseInt(model.getValueAt(membres_table.getSelectedRow(), 0).toString());
        nom_txt.setText(model.getValueAt(membres_table.getSelectedRow(), 1).toString());
        email_txt.setText(model.getValueAt(membres_table.getSelectedRow(), 2).toString());
        date.setDate((Date) model.getValueAt(membres_table.getSelectedRow(), 3));
    }//GEN-LAST:event_membres_tableMouseClicked

    private void mod_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_btnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Voulez vous modifier ce membre!");

        if (nom_txt.getText().isEmpty() || email_txt.getText().isEmpty() || date == null) {
            JOptionPane.showMessageDialog(this, "Remplez vous tous les champs!");
            return;
        }

        if (response == 0) {
            try {
                ms.updateMembre(new Membre(id, nom_txt.getText(), email_txt.getText(), date.getDate()));
                LoadMembres();
                vider();
                mod_btn.setEnabled(false);
                supp_btn.setEnabled(false);
            } catch (Exception ex) {
                Logger.getLogger(Membre_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mod_btnActionPerformed

    private void LoadMembres() {
        model.setRowCount(0);

        try {
            for (Membre m : ms.listMembres()) {
                model.addRow(new Object[]{
                    m.getId(),
                    m.getNom(),
                    m.getEmail(),
                    m.getDateInscription()
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(Membre_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void vider() {
        nom_txt.setText("");
        email_txt.setText("");
        date.setDate(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajou_btn;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable membres_table;
    private javax.swing.JButton mod_btn;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JButton supp_btn;
    // End of variables declaration//GEN-END:variables
}
